# 单个张量的函数运算

In [2]:
import torch

In [3]:
t1 = torch.rand(3, 4)
t1

tensor([[0.1160, 0.5626, 0.0851, 0.7409],
        [0.3103, 0.5866, 0.9324, 0.3886],
        [0.5576, 0.5405, 0.8807, 0.3356]])

In [4]:
t1.sqrt() # 张量求平方根

tensor([[0.3406, 0.7500, 0.2917, 0.8607],
        [0.5571, 0.7659, 0.9656, 0.6234],
        [0.7467, 0.7352, 0.9385, 0.5793]])

In [5]:
torch.sqrt(t1) # 平方根的函数形式

tensor([[0.3406, 0.7500, 0.2917, 0.8607],
        [0.5571, 0.7659, 0.9656, 0.6234],
        [0.7467, 0.7352, 0.9385, 0.5793]])

In [6]:
t1.sqrt_() # 这种形式改变t1的值

tensor([[0.3406, 0.7500, 0.2917, 0.8607],
        [0.5571, 0.7659, 0.9656, 0.6234],
        [0.7467, 0.7352, 0.9385, 0.5793]])

In [7]:
t1

tensor([[0.3406, 0.7500, 0.2917, 0.8607],
        [0.5571, 0.7659, 0.9656, 0.6234],
        [0.7467, 0.7352, 0.9385, 0.5793]])

In [8]:
torch.sum(t1) # 默认对所有元素求和

tensor(8.1547)

In [9]:
torch.sum(t1, 0) # 对第0维的元素求和

tensor([1.6444, 2.2512, 2.1958, 2.0634])

In [10]:
torch.sum(t1, [0, 1]) # 对0， 1维的元素求和

tensor(8.1547)

In [12]:
torch.mean(t1) # 对所有元素求平均

tensor(0.6796)

In [13]:
t1.mean()

tensor(0.6796)

In [14]:
torch.mean(t1, 0) # 对第0维的元素求平均

tensor([0.5481, 0.7504, 0.7319, 0.6878])

# 涉及多个张量的函数运算

In [16]:
t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)

In [17]:
t1.add(t2) # 不改变参与运算的张量值

tensor([[0.2799, 1.0655, 0.9369],
        [1.0296, 0.6460, 1.2424]])

In [18]:
t1 + t2

tensor([[0.2799, 1.0655, 0.9369],
        [1.0296, 0.6460, 1.2424]])

In [19]:
t1.sub(t2) == t1 - t2

tensor([[True, True, True],
        [True, True, True]])

In [20]:
t1.mul(t2) # 乘

tensor([[0.0166, 0.2037, 0.2144],
        [0.2055, 0.0074, 0.3498]])

In [21]:
t1.div(t2) # 除

tensor([[ 0.4383,  0.3061,  1.3559],
        [ 0.3568, 54.4160,  0.5316]])

In [22]:
t1.add_(t2) # 结果保存到t1中 

tensor([[0.2799, 1.0655, 0.9369],
        [1.0296, 0.6460, 1.2424]])

In [23]:
t1, t2

(tensor([[0.2799, 1.0655, 0.9369],
         [1.0296, 0.6460, 1.2424]]),
 tensor([[0.1946, 0.8158, 0.3977],
         [0.7589, 0.0117, 0.8112]]))

# 张量的极值和排序

In [24]:
t = torch.randn(3, 4)
t

tensor([[ 0.7509, -1.5937,  0.1020, -0.9444],
        [ 0.9461, -0.0274,  0.7679,  1.3770],
        [ 0.1404,  0.5138, -0.1843,  0.7331]])

`argmax`和`argmin`用来获取指定维度最大或最小值的索引

In [25]:
torch.argmax(t, 0)

tensor([1, 2, 1, 1])

In [26]:
torch.argmax(t, 1)

tensor([0, 3, 3])

In [27]:
torch.max(t, -1)

torch.return_types.max(
values=tensor([0.7509, 1.3770, 0.7331]),
indices=tensor([0, 3, 3]))

In [28]:
torch.max(t, -1).values

tensor([0.7509, 1.3770, 0.7331])

In [30]:
t.min(0) # 通过张量本身的方法调用

torch.return_types.min(
values=tensor([ 0.1404, -1.5937, -0.1843, -0.9444]),
indices=tensor([2, 0, 2, 0]))

In [31]:
t.sort() # 默认从小到大

torch.return_types.sort(
values=tensor([[-1.5937, -0.9444,  0.1020,  0.7509],
        [-0.0274,  0.7679,  0.9461,  1.3770],
        [-0.1843,  0.1404,  0.5138,  0.7331]]),
indices=tensor([[1, 3, 2, 0],
        [1, 2, 0, 3],
        [2, 0, 1, 3]]))

In [32]:
t.sort(0) # 指定维度排序

torch.return_types.sort(
values=tensor([[ 0.1404, -1.5937, -0.1843, -0.9444],
        [ 0.7509, -0.0274,  0.1020,  0.7331],
        [ 0.9461,  0.5138,  0.7679,  1.3770]]),
indices=tensor([[2, 0, 2, 0],
        [0, 1, 0, 2],
        [1, 2, 1, 1]]))

In [33]:
torch.sort(t, descending=True) # 降序排序

torch.return_types.sort(
values=tensor([[ 0.7509,  0.1020, -0.9444, -1.5937],
        [ 1.3770,  0.9461,  0.7679, -0.0274],
        [ 0.7331,  0.5138,  0.1404, -0.1843]]),
indices=tensor([[0, 2, 3, 1],
        [3, 0, 2, 1],
        [3, 1, 0, 2]]))

# 张量的乘法和张量的缩并

In [35]:
a = torch.randn(3, 4)
b = torch.randn(4, 5)

In [36]:
torch.mm(a, b) # torch函数矩阵相乘

tensor([[ 1.1677, -2.7377, -1.6283, -0.3308, -0.0712],
        [ 1.3637, -3.0081, -1.3796,  0.4200,  0.8895],
        [-1.3427,  0.1237,  1.1927, -0.1227, -1.0071]])

In [37]:
a.mm(b) # 张量方法

tensor([[ 1.1677, -2.7377, -1.6283, -0.3308, -0.0712],
        [ 1.3637, -3.0081, -1.3796,  0.4200,  0.8895],
        [-1.3427,  0.1237,  1.1927, -0.1227, -1.0071]])

In [38]:
a@b # 符号

tensor([[ 1.1677, -2.7377, -1.6283, -0.3308, -0.0712],
        [ 1.3637, -3.0081, -1.3796,  0.4200,  0.8895],
        [-1.3427,  0.1237,  1.1927, -0.1227, -1.0071]])

minibatch 的batch相乘

In [39]:
a = torch.randn(2, 2, 3)
b = torch.randn(2, 3, 4)

In [40]:
torch.bmm(a, b)

tensor([[[ 0.0980, -0.8993,  0.5493, -0.0320],
         [-1.6340, -1.6821,  2.0715, -0.5947]],

        [[-0.9719, -2.0814,  2.6325, -1.0290],
         [-0.1537,  0.1825,  0.6954, -0.0447]]])

In [41]:
a.bmm(b)

tensor([[[ 0.0980, -0.8993,  0.5493, -0.0320],
         [-1.6340, -1.6821,  2.0715, -0.5947]],

        [[-0.9719, -2.0814,  2.6325, -1.0290],
         [-0.1537,  0.1825,  0.6954, -0.0447]]])

In [42]:
a @ b # 根据输入张量的形状计算

tensor([[[ 0.0980, -0.8993,  0.5493, -0.0320],
         [-1.6340, -1.6821,  2.0715, -0.5947]],

        [[-0.9719, -2.0814,  2.6325, -1.0290],
         [-0.1537,  0.1825,  0.6954, -0.0447]]])

对于更高维度的张量，需要用到爱因斯坦求和乘法，指定维度

In [43]:
torch.einsum('bnk,bkl->bnl', a, b)

tensor([[[ 0.0980, -0.8993,  0.5493, -0.0320],
         [-1.6340, -1.6821,  2.0715, -0.5947]],

        [[-0.9719, -2.0814,  2.6325, -1.0290],
         [-0.1537,  0.1825,  0.6954, -0.0447]]])

# 张量的拼接和分割

- torch.stack 通过传入的张量列表，同时指定并创建一个维度，把列表的张量沿着该维度堆叠起来，并返回堆叠以后的张量。传入的张量列表中所有的张量大小必须一致
- torch.cat 与stack的区别是张量列表中的数据本来就有维度，不用创建
- torch.split 叠加操作的反向操作，输出是沿着某个维度分割后的列表，需要传入三个参数：分割后的张量，分割后维度的大小，分割的维度
- torch.chunk 和split函数的功能类似，区别在于前者传入参数是分割的段数，输入张量在该维度的大小需要被分割的段数整除

In [44]:
t1 = torch.randn(3, 4)
t2 = torch.randn(3, 4)
t3 = torch.randn(3, 4)
t4 = torch.randn(3, 2)

In [45]:
torch.stack([t1, t2, t3], -1).shape

torch.Size([3, 4, 3])

In [46]:
torch.stack([t1, t2, t3], 1).shape


torch.Size([3, 3, 4])

In [48]:
torch.cat([t1, t2, t3], -1).shape

torch.Size([3, 12])

In [1]:
import torch

In [2]:
a = torch.randn(3, 6)

In [3]:
a.split([1, 2, 3], -1) # 通过列表指定分成的大小

(tensor([[-0.5847],
         [-0.7526],
         [ 0.0106]]),
 tensor([[-0.8095,  0.4320],
         [ 1.5990,  0.9240],
         [ 1.8498, -0.2866]]),
 tensor([[-1.8227, -0.0788,  2.0047],
         [-0.6908,  1.6348,  0.1549],
         [ 1.2243,  0.0380, -1.2884]]))

In [4]:
torch.split(a, 3, -1) # 通过整数，需要指定的维度能够整除

(tensor([[-0.5847, -0.8095,  0.4320],
         [-0.7526,  1.5990,  0.9240],
         [ 0.0106,  1.8498, -0.2866]]),
 tensor([[-1.8227, -0.0788,  2.0047],
         [-0.6908,  1.6348,  0.1549],
         [ 1.2243,  0.0380, -1.2884]]))

In [5]:
a.chunk(3, -1) # 这里的3表示分成3个

(tensor([[-0.5847, -0.8095],
         [-0.7526,  1.5990],
         [ 0.0106,  1.8498]]),
 tensor([[ 0.4320, -1.8227],
         [ 0.9240, -0.6908],
         [-0.2866,  1.2243]]),
 tensor([[-0.0788,  2.0047],
         [ 1.6348,  0.1549],
         [ 0.0380, -1.2884]]))

# 张量维度的扩增和压缩

In [6]:
t = torch.rand(3, 4)
t.shape

torch.Size([3, 4])

In [7]:
t.unsqueeze(-1).shape

torch.Size([3, 4, 1])

In [8]:
t.unsqueeze(-1).unsqueeze(-1).shape

torch.Size([3, 4, 1, 1])

In [9]:
t = torch.randn(3, 4, 1)
t.shape

torch.Size([3, 4, 1])

In [1]:
t.squeeze(-1).shape

NameError: name 't' is not defined