# 简单线性回归

In [2]:
import torch 
import torch.nn as nn

In [7]:
class LinearModel(nn.Module):
    def __init__(self, ndim):
        super(LinearModel, self).__init__()
        self.ndim = ndim

        self.weight = nn.Parameter(torch.randn(ndim, 1))
        self.bias = nn.Parameter(torch.randn(1))

    def forward(self, x):
        return torch.add(torch.mm(x, self.weight), self.bias)

In [8]:
lm = LinearModel(5)

In [9]:
x = torch.randn(4, 5)

In [10]:
lm(x)

tensor([[-0.7419],
        [-2.4253],
        [-0.5803],
        [ 0.6768]], grad_fn=<AddBackward0>)

# 类的实例化和方法调用

- named_parameters, parameters 返回参数生成器
- train, eval 切换训练和测试状态
- named_buffers buffers 表示不需要反向传播更新参数，但是需要更新的参数，如BN层的mean和variance
- named_children, children 获取子模块
- apply 如果需要对所有模块应用一个函数，可以使用apply方法，通过传入一个函数或着匿名函数来递归的应用这些函数
- 改变模块参数数据类型和存储的位置， to方法

In [13]:
lm = LinearModel(5)

In [14]:
x = torch.randn(4, 5)

In [15]:
lm(x)

tensor([[ 2.6166],
        [ 2.2782],
        [-0.7478],
        [ 1.9352]], grad_fn=<AddBackward0>)

In [16]:
lm.named_parameters()

<generator object Module.named_parameters at 0x7ff0f4034430>

In [18]:
list(lm.named_parameters())

[('weight',
  Parameter containing:
  tensor([[ 0.5292],
          [-0.2425],
          [-1.1718],
          [-0.5390],
          [-0.4169]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([1.6088], requires_grad=True))]

In [19]:
list(lm.parameters())

[Parameter containing:
 tensor([[ 0.5292],
         [-0.2425],
         [-1.1718],
         [-0.5390],
         [-0.4169]], requires_grad=True),
 Parameter containing:
 tensor([1.6088], requires_grad=True)]

In [20]:
lm.cuda()

LinearModel()

In [21]:
list(lm.parameters())

[Parameter containing:
 tensor([[ 0.5292],
         [-0.2425],
         [-1.1718],
         [-0.5390],
         [-0.4169]], device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([1.6088], device='cuda:0', requires_grad=True)]

In [22]:
lm.half()

LinearModel()

In [23]:
list(lm.parameters())

[Parameter containing:
 tensor([[ 0.5293],
         [-0.2424],
         [-1.1719],
         [-0.5391],
         [-0.4170]], device='cuda:0', dtype=torch.float16, requires_grad=True),
 Parameter containing:
 tensor([1.6084], device='cuda:0', dtype=torch.float16, requires_grad=True)]