# 损失函数
有两种方法：
- torch.nn.functional库中的函数，通过传入神经网络预测值和目标值来计算算是函数
- torch.nn库里的模块，通过新建一个类实例

In [1]:
import torch

In [2]:
mse = torch.nn.MSELoss()

In [3]:
t1 = torch.randn(5, requires_grad=True)
t2 = torch.randn(5, requires_grad=True)

In [4]:
mse(t1, t2)

tensor(0.7396, grad_fn=<MeanBackward0>)

In [5]:
t1

tensor([-1.6085, -0.8710, -0.9093, -0.3729,  0.8947], requires_grad=True)

In [6]:
t1s = torch.sigmoid(t1)

In [7]:
t2 = torch.randint(0, 2, (5,)).float()

In [8]:
t2

tensor([1., 1., 0., 1., 1.])

In [9]:
bce = torch.nn.BCELoss()

In [10]:
bce(t1s, t2)

tensor(0.9179, grad_fn=<BinaryCrossEntropyBackward>)

In [11]:
bce_logits = torch.nn.BCEWithLogitsLoss()

In [12]:
bce_logits(t1, t2)

tensor(0.9179, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)

In [13]:
N = 10
t1 = torch.randn(5, N, requires_grad=True)
t2 = torch.randint(0, N, (5,))

In [14]:
t1s = torch.nn.functional.log_softmax(t1, -1)

In [15]:
t1s

tensor([[-3.4419, -3.6095, -2.9950, -2.2442, -5.0245, -1.6536, -3.1174, -0.8307,
         -2.8474, -3.0175],
        [-1.6441, -1.3460, -3.1711, -2.4874, -3.1113, -2.3566, -2.5438, -2.7046,
         -2.5721, -2.8078],
        [-3.2277, -2.3364, -2.4705, -2.3706, -2.7748, -2.3268, -1.8621, -1.8807,
         -1.7115, -3.2881],
        [-3.3912, -1.8279, -1.8819, -2.6290, -3.7985, -2.0275, -2.0662, -2.0035,
         -1.9618, -3.6911],
        [-3.5460, -1.7787, -2.8073, -2.6770, -1.4269, -2.3466, -3.6317, -1.9179,
         -2.2200, -2.8925]], grad_fn=<LogSoftmaxBackward>)

# 优化器

In [18]:
lm = torch.nn.Linear(30, 15)

In [19]:
optim = torch.optim.SGD(lm.parameters(), lr=1e-6)

```python
# 对模型的不同部分设置不同的学习率
optim.SGD([
    {'params': model.base.parameters()},
    {'params': model.classifier.parameters(), 'lr'=1e-3},
], lr=1e-2, momentum=0.9)
```

torch.optim 包还提供了学习率衰减的相关类，这些类都在torch.optim.lr_scheduler中

In [21]:
schduler = torch.optim.lr_scheduler.StepLR(optim, step_size=30, gamma=0.1)