## Python列表和Numpy数组转换为Pytorch张量

In [1]:
import numpy as np 
import torch

In [2]:
torch.tensor([1, 2, 3, 4]) # 将列表转为张量

tensor([1, 2, 3, 4])

In [4]:
torch.tensor([1, 2, 3, 4]).dtype # 查看数据类型 

torch.int64

In [5]:
torch.tensor([1, 2, 3, 4], dtype=torch.float32) # 指定创建的数据类型

tensor([1., 2., 3., 4.])

In [6]:
torch.tensor(range(1, 10)) # 转换迭代器为张量

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
torch.tensor(np.array([1, 2, 3, 4])) # 转换numpy数组为Pytorch张量

tensor([1, 2, 3, 4])

In [8]:
torch.randn(3, 3)

tensor([[-0.6974,  0.3120,  2.0762],
        [ 0.0372, -0.9844,  0.3371],
        [ 1.5765, -1.3222,  0.7812]])

In [9]:
torch.randn(3, 3).to(torch.int) # 类型转换

tensor([[ 0, -2,  0],
        [ 0,  0, -1],
        [ 1, -1,  0]], dtype=torch.int32)

### 张量创建的方法

- 通过torch.tensor，可以把已有的列表或者numpy数据转为张量
- 通过pytorch内置的函数创建

In [11]:
torch.rand(3, 3) # 0, 1均匀分布

tensor([[0.6116, 0.0447, 0.9723],
        [0.8251, 0.8646, 0.7288],
        [0.9402, 0.2453, 0.1350]])

In [12]:
torch.randn(2, 3, 4) # 标准正态分布

tensor([[[-1.7402, -2.9717, -0.0682,  1.8217],
         [ 0.6076, -0.6944,  2.2820,  1.0732],
         [ 0.3321,  1.8219, -2.2338, -1.3025]],

        [[ 0.0837,  0.1723,  0.1320, -0.1364],
         [ 0.7051, -0.2636, -0.8213, -0.6116],
         [ 0.0302,  1.2663,  1.1148, -1.2247]]])

In [13]:
torch.zeros(2, 2, 2) # 全零

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [14]:
torch.ones(1, 2, 3) # 全一

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [15]:
torch.eye(3) # 单位矩阵

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
torch.randint(1, 10, (3, 3)) # 生成1-10之间均匀分布的整数

tensor([[5, 6, 1],
        [1, 5, 6],
        [7, 1, 5]])

- 通过一直张量创建形状相同的张量

In [19]:
t = torch.randn(3, 3) # 生成一个随机正态分布的张量

In [20]:
torch.zeros_like(t) # 生成一个元素全为0的张量

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.ones_like(t) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
torch.rand_like(t)

tensor([[0.4139, 0.0228, 0.6687],
        [0.4484, 0.8305, 0.3623],
        [0.9167, 0.2757, 0.2155]])

In [23]:
torch.randn_like(t)

tensor([[ 0.3741,  0.1107, -1.2638],
        [ 0.6456, -0.0989, -0.5506],
        [-0.9347,  0.6598,  1.4923]])

In [27]:
torch.randint_like(t, 1, 10)

tensor([[4., 2., 1.],
        [4., 2., 3.],
        [7., 1., 2.]])