## Python列表和Numpy数组转换为Pytorch张量

In [1]:
import numpy as np 
import torch

In [2]:
torch.tensor([1, 2, 3, 4]) # 将列表转为张量

tensor([1, 2, 3, 4])

In [4]:
torch.tensor([1, 2, 3, 4]).dtype # 查看数据类型 

torch.int64

In [5]:
torch.tensor([1, 2, 3, 4], dtype=torch.float32) # 指定创建的数据类型

tensor([1., 2., 3., 4.])

In [6]:
torch.tensor(range(1, 10)) # 转换迭代器为张量

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
torch.tensor(np.array([1, 2, 3, 4])) # 转换numpy数组为Pytorch张量

tensor([1, 2, 3, 4])

In [8]:
torch.randn(3, 3)

tensor([[-0.6974,  0.3120,  2.0762],
        [ 0.0372, -0.9844,  0.3371],
        [ 1.5765, -1.3222,  0.7812]])

In [9]:
torch.randn(3, 3).to(torch.int) # 类型转换

tensor([[ 0, -2,  0],
        [ 0,  0, -1],
        [ 1, -1,  0]], dtype=torch.int32)

### 张量创建的方法

- 通过torch.tensor，可以把已有的列表或者numpy数据转为张量
- 通过pytorch内置的函数创建

In [11]:
torch.rand(3, 3) # 0, 1均匀分布

tensor([[0.6116, 0.0447, 0.9723],
        [0.8251, 0.8646, 0.7288],
        [0.9402, 0.2453, 0.1350]])

In [12]:
torch.randn(2, 3, 4) # 标准正态分布

tensor([[[-1.7402, -2.9717, -0.0682,  1.8217],
         [ 0.6076, -0.6944,  2.2820,  1.0732],
         [ 0.3321,  1.8219, -2.2338, -1.3025]],

        [[ 0.0837,  0.1723,  0.1320, -0.1364],
         [ 0.7051, -0.2636, -0.8213, -0.6116],
         [ 0.0302,  1.2663,  1.1148, -1.2247]]])

In [13]:
torch.zeros(2, 2, 2) # 全零

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [14]:
torch.ones(1, 2, 3) # 全一

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [15]:
torch.eye(3) # 单位矩阵

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
torch.randint(1, 10, (3, 3)) # 生成1-10之间均匀分布的整数

tensor([[5, 6, 1],
        [1, 5, 6],
        [7, 1, 5]])

- 通过一直张量创建形状相同的张量

In [19]:
t = torch.randn(3, 3) # 生成一个随机正态分布的张量

In [20]:
torch.zeros_like(t) # 生成一个元素全为0的张量

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.ones_like(t) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
torch.rand_like(t)

tensor([[0.4139, 0.0228, 0.6687],
        [0.4484, 0.8305, 0.3623],
        [0.9167, 0.2757, 0.2155]])

In [23]:
torch.randn_like(t)

tensor([[ 0.3741,  0.1107, -1.2638],
        [ 0.6456, -0.0989, -0.5506],
        [-0.9347,  0.6598,  1.4923]])

In [27]:
torch.randint_like(t, 1, 10)

tensor([[4., 2., 1.],
        [4., 2., 3.],
        [7., 1., 2.]])

- 通过已知张量创建形状不同但数据类型相同的张量

In [7]:
t = torch.randn((3, 3), dtype=torch.float64)

In [8]:
t

tensor([[-0.2892, -2.3305,  1.4133],
        [-1.0979,  0.2384, -1.8423],
        [-0.0386, -0.1513, -1.0705]], dtype=torch.float64)

In [9]:
t.new_tensor([1, 2, 3]) # 新的张量只是类型相同

tensor([1., 2., 3.], dtype=torch.float64)

In [10]:
t.new_zeros((3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

### 张量的存储设备

In [11]:
!nvidia-smi

Sun Nov  1 18:02:45 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8     3W /  N/A |    203MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [12]:
torch.randn(3, 3, device='cpu')

tensor([[ 0.5837, -0.2005, -0.0091],
        [ 0.0835, -0.2671, -0.9937],
        [ 0.6844, -0.6452,  0.8705]])

In [14]:
a = torch.randn(3, 3, device='cuda:0')
print(a)

tensor([[ 0.1710, -0.8099,  0.3898],
        [-0.0520,  0.5442, -0.8056],
        [ 0.2673, -0.6154,  0.6585]], device='cuda:0')


In [15]:
a.device # 张量的设备

device(type='cuda', index=0)

In [16]:
torch.rand(3, 3).cuda(0).device # 通过cuda方法将tensor放到GPU

device(type='cuda', index=0)

In [18]:
torch.randn(3, 3).to('cuda:0').device # 通过to方法将tensor放到GPU

device(type='cuda', index=0)

### 张量维度操作

In [19]:
t = torch.randn(3, 4, 5)

In [20]:
t.ndimension() # 获取维度的数目

3

In [21]:
t.nelement() # 获取元素的总数目

60

In [22]:
t.size() # 获取该张量每个维度的大小，调用方法

torch.Size([3, 4, 5])

In [23]:
t.shape # 获取张量的维度，访问属性

torch.Size([3, 4, 5])

In [24]:
t.size(0) # 获得维度0的大小

3

In [25]:
t = torch.rand(12)

In [26]:
t.view(3, 4) # 向量改变形状为 3*4 的矩阵，不改变底层数据，改变view后张量会改变原来的张量

tensor([[0.8621, 0.1244, 0.6044, 0.1869],
        [0.6963, 0.5734, 0.4883, 0.2445],
        [0.2256, 0.2444, 0.2149, 0.1279]])

In [27]:
t

tensor([0.8621, 0.1244, 0.6044, 0.1869, 0.6963, 0.5734, 0.4883, 0.2445, 0.2256,
        0.2444, 0.2149, 0.1279])

In [29]:
t.data_ptr() # 获取张量的数据指针

94609675529024

In [30]:
t.view(3, 4).data_ptr() # 指针不变

94609675529024

In [32]:
t.view(4, 3).contiguous().data_ptr() # 使用contiguous,如果张量的形状和初始维度形状的信息兼容，则会返回当前张量，否则就会返回新的张量

94609675529024

In [33]:
t.view(4, 3).transpose(0, 1).contiguous().data_ptr() # 这里会返回一个新的张量

94609675087360

使用reshpe方法相当于连续调用resize和contiguous

### 张量的索引和切片

In [35]:
t = torch.randn(2, 3, 4)

In [36]:
t[1, 2, 3] # 取在0维1号，1维2号，2维3号的元素

tensor(0.9655)

In [37]:
t[:, 1:-1, 1:3]

tensor([[[-0.4711,  0.7185]],

        [[-0.0153,  1.0690]]])

In [38]:
t

tensor([[[ 1.0214,  0.4824, -0.8190, -0.7381],
         [-0.6275, -0.4711,  0.7185, -2.1205],
         [-0.5769,  0.5260,  0.9779, -0.1027]],

        [[-0.7817,  1.8773, -0.4806, -1.6804],
         [ 0.0275, -0.0153,  1.0690,  0.2106],
         [ 0.9030,  0.2104,  1.0886,  0.9655]]])

In [39]:
t > 0 

tensor([[[ True,  True, False, False],
         [False, False,  True, False],
         [False,  True,  True, False]],

        [[False,  True, False, False],
         [ True, False,  True,  True],
         [ True,  True,  True,  True]]])

In [40]:
t[t>0] # 张量大于0的值

tensor([1.0214, 0.4824, 0.7185, 0.5260, 0.9779, 1.8773, 0.0275, 1.0690, 0.2106,
        0.9030, 0.2104, 1.0886, 0.9655])